services:
  - type: web
    name: youtube-ai-podcast
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: DEBUG
        value: "False"
      - key: LOG_LEVEL
        value: "INFO"
