# プロンプトテンプレート設定

# メインコンテンツ生成プロンプト
main_content_prompt: |
  あなたはYouTubeポッドキャストのコンテンツを生成するAIアシスタントです。
  
  以下の情報を基に、魅力的で興味深いポッドキャストコンテンツを作成してください：
  
  データ: {data}
  
  要件:
  - 15-20分程度の長さのコンテンツ
  - 聞き手が興味を持てるトピック
  - 自然な会話形式
  - 適切な導入と結論
  - 具体的な例やエピソードを含める
  
  出力形式:
  - タイトル
  - 概要
  - メインコンテンツ（会話形式）
  - キーポイント
  - 結論

# メタデータ生成プロンプト
metadata_prompt: |
  以下のコンテンツを基に、YouTube動画用のメタデータを生成してください：
  
  コンテンツ: {content}
  
  生成する項目:
  - タイトル（60文字以内）
  - 説明文（5000文字以内）
  - タグ（15個以内）
  - カテゴリ
  - サムネイルの提案

# 音声生成プロンプト
audio_prompt: |
  以下のテキストを自然で聞きやすい音声に変換してください：
  
  テキスト: {text}
  
  要件:
  - 日本語の自然な発音
  - 適切な間とリズム
  - 感情豊かな表現
  - 聞きやすい音量とスピード

# 動画生成プロンプト
video_prompt: |
  以下の音声とコンテンツを基に、魅力的な動画を作成してください：
  
  音声ファイル: {audio_path}
  コンテンツ: {content}
  
  要件:
  - 1920x1080の解像度
  - 適切な背景画像
  - テキストの表示
  - スムーズなトランジション
  - 音声と同期した動画

# エラーハンドリングプロンプト
error_handling_prompt: |
  以下のエラーが発生しました：
  
  エラー: {error}
  コンテキスト: {context}
  
  対処法を提案してください：
  - エラーの原因分析
  - 解決策の提案
  - 再試行の方法
  - 代替手段の提案
