# プロンプトテンプレート設定

# メインコンテンツ生成プロンプト
main_content_prompt: |
  あなたはYouTubeポッドキャストのコンテンツを生成するAIアシスタントです。
  
  以下の情報を基に、魅力的で興味深いポッドキャストコンテンツを作成してください：
  
  データ: {data}
  
  要件:
  - 15-20分程度の長さのコンテンツ
  - 聞き手が興味を持てるトピック
  - 自然な会話形式
  - 適切な導入と結論
  - 具体的な例やエピソードを含める
  
  出力形式:
  - タイトル
  - 概要
  - メインコンテンツ（会話形式）
  - キーポイント
  - 結論

# メタデータ生成プロンプト
metadata_prompt: |
  以下のコンテンツを基に、YouTube動画用のメタデータを生成してください：
  
  コンテンツ: {content}
  
  生成する項目:
  - タイトル（60文字以内）
  - 説明文（5000文字以内）
  - タグ（15個以内）
  - カテゴリ
  - サムネイルの提案

# 音声生成プロンプト
audio_prompt: |
  以下のテキストを自然で聞きやすい音声に変換してください：
  
  テキスト: {text}
  
  要件:
  - 日本語の自然な発音
  - 適切な間とリズム
  - 感情豊かな表現
  - 聞きやすい音量とスピード

# 動画生成プロンプト
video_prompt: |
  以下の音声とコンテンツを基に、魅力的な動画を作成してください：
  
  音声ファイル: {audio_path}
  コンテンツ: {content}
  
  要件:
  - 1920x1080の解像度
  - 適切な背景画像
  - テキストの表示
  - スムーズなトランジション
  - 音声と同期した動画

# エラーハンドリングプロンプト
error_handling_prompt: |
  以下のエラーが発生しました：
  
  エラー: {error}
  コンテキスト: {context}
  
  対処法を提案してください：
  - エラーの原因分析
  - 解決策の提案
  - 再試行の方法
  - 代替手段の提案

# YouTube メタデータ生成プロンプト
youtube_metadata_prompt: |
  以下の台本とトピック情報から、YouTube動画用のメタデータを生成してください：
  
  【台本】
  {script_content}
  
  【トピック情報】
  {topics_data}
  
  以下の項目を生成してください：
  
  1. **タイトル（70文字以内）**
     - SEO最適化
     - クリックしたくなる内容
     - 数字や具体性を含める
  
  2. **説明文**
     - 冒頭200文字: 動画の概要
     - 各トピックの要約（3-5個）
     - 出典URL明記（著作権対策として必須）
     - 合計5000文字以内
  
  3. **タグ（15個以内）**
     - トピックに関連するキーワード
     - SEO効果の高いタグ
  
  4. **サムネイル用キャッチコピー（16文字以内、1行）**
     - インパクトのある短いフレーズ
     - 数字や具体性を含める
     - 改行なし、1行で完結
  
  出力形式（JSON）:
  {{
    "title": "...",
    "description": "...",
    "tags": ["tag1", "tag2", ...],
    "thumbnail_text": "..."
  }}

# コメント生成プロンプト（毒舌の女の子設定）
comment_generation_prompt: |
  以下の動画内容について、動画の最初のコメントを生成してください：
  
  【動画内容】
  {script_content}
  
  【設定】
  あなたは、この対談を聞いている女の子です。
  普段は真面目に勉強しているように見えますが、実は毒舌です。
  
  要件：
  - 100-200文字程度
  - 鋭い視点や皮肉を含める
  - でも嫌味にならない程度に
  - ちょっとクスッとくる内容
  - 動画の内容に対する的確なツッコミ
  
  出力形式:
  コメントテキストのみを出力してください。

# サムネイル用テキスト生成プロンプト
thumbnail_text_prompt: |
  以下の動画タイトルとトピックから、サムネイル用のキャッチコピーを生成してください：
  
  【タイトル】
  {title}
  
  【トピック】
  {topics}
  
  要件:
  - 25-35文字程度
  - インパクトがある
  - 数字や具体性を含める
  - 読みやすく、一目で理解できる
  - サムネイルに表示して映える
  
  出力:
  キャッチコピーのみを出力してください。
